import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "public",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <div>
      <h1 className="">public</h1>
      {children}
    </div>
  );
}
